# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb36c4edbb2d370f8ed874630d5e8e4c9ad8e1784271631c1a28fa8f5cb6810f7dd0ca1fb3518d20d2e37dc98303f53a36896928351f43111da8e821b758e1c

test:
  secret_key_base: bb4caf9a87424a76585ca77b569369ee278d6a6c7fd7013a6a4e2e151e40bb6ae7861af134a6c6a7c7b12ad24af44dc343613d0ae0eb878b1dfc48611f41a6d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
